site/controllers/Create.py
from flask import *
from AccessManagement import login_required
from ThriftClient import thrift_client


create = Blueprint('create', __name__, template_folder='templates')

@create.route('/create', methods=['GET', 'POST'])
@login_required
def create_route():
	options = {}
	try:
		# Retrieve pre-configured services.
		services_list = []
		for service in thrift_client.SERVICES.values():
			host, port = service.get_host_port()
			services_list.append((service.name, host, port))
		options['service_list']= sorted(services_list, key=lambda i: i[0])
	except Exception as e:
		log(e)
		options['error'] = e			
	return render_template("create.html", **options)

site/controllers/Infer.py
from flask import *
from AccessManagement import login_required
from ThriftClient import thrift_client
from QueryClassifier import query_classifier
from Utilities import log, check_image_extension
import os

infer = Blueprint('infer', __name__, template_folder='templates')


@infer.route('/infer', methods=['GET', 'POST'])
@login_required
def infer_route():
	options = {}
	if os.environ.get('ASR_ADDR_PORT'):
		options['asr_addr_port'] = os.environ.get('ASR_ADDR_PORT')
	else:
		options['asr_addr_port'] = 'ws://localhost:8081'
	try:
		form = request.form
		# Deal with POST requests.
		if request.method == 'POST':
			# If the request does not contain an "op" field.
			if not 'op' in form:
				raise RuntimeError('Did you click the Ask button?')
			# When the "op" field is equal to "add_image".
			elif form['op'] == 'infer':
				# Check input file.
				upload_file = request.files['file']
				if upload_file.filename != '':
					check_image_extension(upload_file)
				print '@@@@@@@@@@', form['speech_input']
				# Classify the query.
				services_needed = \
					query_classifier.predict(form['speech_input'], upload_file)
				options['result'] = thrift_client.infer(session['username'], 
					services_needed, form['speech_input'], upload_file.read())
				log('Result ' + options['result'])
				# Check if Calendar service is needed.
				# If so, JavaScript needs to receive the parsed dates.
				if services_needed.has_service('CA'):
					options['dates'] = options['result']
					options['result'] = None
					return render_template('infer.html', **options)
			else:
				raise RuntimeError('Did you click the Ask button?')
	except Exception as e:
		log(e)
		if str(e) == 'TSocket read 0 bytes':
			e = 'Back-end service encountered a problem'
		options['error'] = e
		return render_template('infer.html', **options)
	# Display.
	return render_template('infer.html', **options)

site/controllers/Learn.py
from flask import *
import Database, ThriftClient
import hashlib, datetime
from AccessManagement import login_required
from Database import database 
from ThriftClient import thrift_client
from Utilities import log, check_image_extension, check_text_input


learn = Blueprint('learn', __name__, template_folder='templates')

@learn.route('/learn', methods=['GET', 'POST'])
@login_required
def learn_route():
	options = {}
	username = session['username']
	try:
		form = request.form
		# Deal with POST requests.
		if request.method == 'POST':
			# If the request does not contain an "op" field.
			if not 'op' in request.form:
				raise RuntimeError('Did you click the button?')
			# Add image knowledge.
			elif form['op'] == 'add_image':
				image_type = 'image'
				label = form['label']
				# Check the uploaded image.
				upload_file = request.files['file']
				if upload_file.filename == '':
					raise RuntimeError('Empty file is not allowed')
				check_image_extension(upload_file)
				# Check the label of the image.
				check_text_input(label)
				# Check whether the user can add one more image.
				database.check_add_image(username)
				# Generate the id.
				image_data = upload_file.read()
				image_id = hashlib.md5(username +
					str(datetime.datetime.now())).hexdigest()
				# Send the image to IMM.
				upload_file.close()
				thrift_client.learn_image(username, image_type, image_data,
					image_id)
				# Add the image into the database.
				database.add_image(username, image_data, label, image_id)
			# Delete image knowledge.
			elif form['op'] == 'delete_image':
				image_type = 'unlearn'
				image_id = form['image_id']
				# Send the unlearn request to IMM.
				thrift_client.learn_image(username, image_type, '', image_id)
				# Delete the image from the database.
				database.delete_image(username, image_id)	
			# Add text knowledge.
			elif form['op'] == 'add_text' or form['op'] == 'add_url':
				text_type = 'text' if form['op'] == 'add_text' else 'url'
				text_data = form['knowledge']
				# Check the text knowledge.
				check_text_input(text_data)
				# Check whether the user can add one more piece of text.
				database.check_add_text(username)
				# Generate the id.
				text_id = hashlib.md5(username + text_data +
					str(datetime.datetime.now())).hexdigest()
				# Send the text to QA.
				thrift_client.learn_text(username, text_type,
						text_data, text_id)
				# Add the text knowledge into the database.
				database.add_text(username, text_type, text_data, text_id)	
			# Delete text knowledge.
			elif form['op'] == 'delete_text':
				text_type = 'unlearn'
				text_id = form['text_id']
				# Send the unlearn request to QA.
				thrift_client.learn_text(username, text_type, '', text_id)
				# Delete the text from into the database.
				database.delete_text(username, text_id)			
			else:
				raise RuntimeError('Did you click the button?')
	except Exception as e:
		log(e)
		if str(e) == 'TSocket read 0 bytes':
			e = 'Back-end service encountered a problem'
		options['error'] = e
	try:
		# Retrieve knowledge.
		options['pictures'] = database.get_images(username)
		options['text'] = database.get_text(username)
	except Exception as e:
		log(e)
		options['error'] = e
	return render_template('learn.html', **options)

site/controllers/LoginForm.py
from wtforms import Form, TextField, PasswordField


class LoginForm(Form):
	# Fields of the form.
	username = TextField('Username')
	
	password = PasswordField('Password')

site/controllers/Main.py
import requests, json
from flask import *


main = Blueprint('main', __name__, template_folder='templates')

@main.route('/', methods=['GET',])
def main_route():
	# Display
	return render_template("index.html")

@main.route('/contact', methods=['GET',])
def contact_route():
	# Display
	return render_template("contact.html")

site/controllers/User.py
from flask import *
from Database import database
from RegistrationForm import RegistrationForm
from LoginForm import LoginForm
from AccessManagement import login_required


user = Blueprint('user', __name__, template_folder='templates')

@user.route('/signup', methods=['GET', 'POST'])
def signup_route():
	# Check if the viewer already has a session.
	if 'logged_in' in session:
		# Display.
		return redirect(url_for('main.main_route')) # cannot register again		
	# Retrieve the registration form.
	form = RegistrationForm(request.form)
	options = {
		'error': []
	}
	# Deal with POST requests.
	if request.method == "POST":
		if form.validate():
			# Insert the user into database.
			database.add_user(form.username.data, form.firstname.data,
				form.lastname.data, form.password1.data,
				form.email.data)
			# Display.
			return redirect(url_for('user.login_route')) # still need to log in
		else:
			options['error'] = []
			for error_list in form.errors.items():
				options['error'] += error_list[1]
			# note: form.errors.items() is like:
			#       [('username', ['error message', 'error message']),
			#       ('password', ['error message'])]
			# Display.
			return render_template("signup.html", form=form, **options)
	# Display.
	return render_template("signup.html", form=form, **options)

@user.route('/login', methods=['GET', 'POST'])
def login_route():
	# Retrieve the registration form.
	form = LoginForm(request.form)
	options = {
		'error': []
	}
	# Deal with POST requests.
	if request.method == "POST":
		if form.validate():
			if not database.username_exists(form.username.data):
				options['error'] = ['Username does not exist']
				# Display.
				return render_template("login.html", form=form, **options)
			# Check if the password is correct.
			password_is_correct = database.check_password(form.username.data, 
				form.password.data)
			if not password_is_correct:
				options['error'] = \
					['Password is incorrect for the specified username']
				# Display.
				return render_template("login.html", form=form, **options)
			# Update session.
			session['logged_in'] = True
			session['username'] = form.username.data
			# Get the url argument.
			url = request.args.get('url')
			if not url is None: # requested a private page and passed the check
				return redirect(url)
			# Display.
			return redirect(url_for('main.main_route'))
	# Display.
	return render_template("login.html", form=form, **options)

@user.route('/logout', methods=['GET', 'POST'])
@login_required
def logout_route():
	# Remove contents of cookie.
	session.clear()
	# Redirect to the default home page.
	return redirect(url_for('main.main_route'))

site/templates/base.html
<!DOCTYPE html PUBLIC "-//w3c//dtd html 4.0 transitional//en">

{% block styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css')}}" />
<link rel="stylesheet" href="{{ url_for('static', filename='css/sticky-footer.css')}}" />
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/jquery-1.10.2.min.js')}}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.min.js')}}"></script>
{% endblock %}

<head>
<base href="/">
<meta charset="UTF-8" />
<meta http-equiv="Pragma" content="no-cache">
<!--<meta name="viewport" content="width=device-width, initial-scale=1">-->
<title>Lucida</title>
<link rel="icon" href="{{ url_for('static', filename='image/lucida.ico')}}" type="image/x-icon" />
</head>

<body>
<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<a id="nav_home" class="navbar-brand" href="{{ url_for('main.main_route') }}">Lucida</a>
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		 	{% if session['logged_in'] %}
			<ul class="nav navbar-nav navbar-left">
				<li><a id="nav_albums" href="{{ url_for('create.create_route') }}">Create</a></li>
		 	</ul>

			<ul class="nav navbar-nav navbar-left">
				<li><a id="nav_albums" href="{{ url_for('learn.learn_route') }}">Learn</a></li>
		 	</ul>

			<ul class="nav navbar-nav navbar-left">
				<li><a id="nav_albums" href="{{ url_for('infer.infer_route') }}">Infer</a></li>
		 	</ul>

			<ul class="nav navbar-nav navbar-right">
				<li><a id="nav_logout" href="{{ url_for('user.logout_route') }}">Log out</a><li>
		 	</ul>

			<ul class="nav navbar-nav navbar-right">
				<li><a>Logged in as {{ session['username'] }}</a></li>
		 	</ul>
		 	{% endif %}

		 	{% if not session['logged_in'] %}
			<ul class="nav navbar-nav navbar-right">
				<li><a id="home_user_create" href="{{ url_for('user.signup_route') }}">Sign up</a></li>
		 	</ul>

			<ul class="nav navbar-nav navbar-right">
				<li><a id="home_login" href="{{ url_for('user.login_route') }}">Log in</a></li>
		 	</ul>
		 	{% endif %}	 
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container -->
</nav>

<div>
<br><br><br><br>
	 {% block content %}{% endblock %}
</div>

<footer class="footer">
 	<div class="container">
		<p class="text-muted">By Yunsheng Bai.
		<a href="{{ url_for('main.contact_route') }}">Contact</a></p>
	</div>
</footer>
</body>
</html>

site/templates/contact.html
{% extends "base.html" %}

{% block content %}
<div class="container">
	<div class="row">
		<p style="color:gray">Main » Contact</p>
	</div>

	<div class="page-header">
		<h1>Developers</h1>
	</div>

	<div class="row">
		<ul>
			<li><p class="lead">Yunsheng Bai: yba AT umich.edu</li>
		</ul>
	</div>

	<br><br>

	<div class="row">
		<a href="{{ url_for('main.main_route') }}" class="btn btn-default">Back to Main</a>
	</div>

	<br>
</div>
{% endblock %}

site/templates/create.html
{% extends "base.html" %}

{% block content %}
<div class="container">
	<div class="row">
		<p style="color:gray">Main » Create</p>
	</div>

	<div class="container">
		<div class="row">
			<p><h3>List of Services</h3></p>
		</div>
	</div>

	<div class="container">
		<table class="table table-striped table-hover">
			<thead>
				<tr>
					<th>Service name</th>
					<th>Host</th>
					<th>Port</th>
				</tr>
			</thead>
			<tbody>
				{% for i in service_list %}
				<tr>
					<td>{{ i[0] }}</td>
					<td>{{ i[1] }}</td>
					<td>{{ i[2] }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>

</div>
{% endblock %}

site/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="container">
	<div class="page-header">
		<h1><center>Welcome to Lucida!</center></h1>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-4" style="background-color: #FF9999"><h4><center>Create</center><h4></div>
		<div class="col-md-4" style="background-color: #F2F5A9"><h4><center>Learn</center><h4></div>
		<div class="col-md-4" style="background-color: #99CCFF"><h4><center>Infer</center><h4></div>
	</div>

	<br>

	{% if not session['logged_in'] %}
		<div class="row">
			<p class="lead">Please sign up or log in to start. </p>
		</div>
	{% else %}
		<div class="row">
			<p class="lead">Click "Create," Learn," or "Infer" above. </p>
		</div>		
	{% endif %}
</div>

<div class="container">
	<div class="row">
		<div class="col-md-1"></div>
		<div class="col-md-10" style="background-color: #B8D192">
			<h4><center>Lucida: Infrastructure to Study Emerging Intelligent Web Services</center></h4>
			<p>As Intelligent Personal Assistants (IPA) such as Apple Siri, Google Now, Microsoft Cortana, and Amazon Echo continue to gain traction, webservice companies are now providing image, speech, and natural language processing web services as the core applications in their datacenters. These emerging applications require machine learning and are known to be significantly more compute intensive than traditional cloud based web services, giving rise to a number of questions surrounding the designs of server and datacenter architectures for handling this volume of computation.</p>
		</div>
		<div class="col-md-1"></div>
	</div>
</div>

<br>
{% endblock %}

site/templates/infer.html
{% extends "base.html" %}

{% block content %}

{% if dates %}
<meta id="dates" data-name="{{ dates }}"> <!-- passed to calendar.js -->
<script src="https://apis.google.com/js/client.js?onload=checkAuth&output=embed"></script>
<script src="{{ url_for('static', filename='js/calendar.js')}}"></script>
{% endif %}

<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/asr.css')}}">

<div class="container">
	<div class="row">
		<p style="color:gray">Main » Infer</p>
	</div>

	<div class="container">
		<div class="row">
			<p><h3>Ask a question:</h3></p>
		</div>
	</div>

	<div class="container">
		<form id="infer_form" method="post" enctype="multipart/form-data">
			<input name="op" type="hidden" value="infer" />

			<div class="form-group">
				<label>Image input</label>
				<input id="image_input" type="file" name="file" size="60">
				<p class="help-block">Upload your picture!</p>
			</div>

			<div class="form-group">
				<label>Speech input</label>
			</div>
	</div>

	{% if error %}
	<strong class=text-danger><p class="error">{{ error }}</p></strong>
	{% endif %}
</div>

<div class="blended_grid">
	<div class="containerResponse">
		<table style="width:800px" align="center">
			<tr>
				<td>
					<div id="recbutton" class="disabled" onclick="clearTranscription(); toggleListening();"></div>
				</td>
				<td><div class="wrap">
						<textarea id="trans" name="speech_input" form="infer_form"></textarea>
					</div>
				</td>
				<td><div class="wrapr">
						<textarea readonly id="clinc" style="margin-right: 10px">{% if result %}{{ result }}{% endif %}</textarea>
					</div>
				</td>
			</tr>
			<tr>
				<td></td>
				<td>
					<img src="{{ url_for('static', filename='image/user.png')}}" style="float: left; width: 70px;">
				</td>
				<td>
				 	<img src="{{ url_for('static', filename='image/lucida.jpg')}}" style="float: right; width: 80px;">
				</td>
			</tr>
			<tr>
				<td></td>
				<td colspan="2">
				<br><br>


			<div class="form-group">
				<input id="file_submit" type="submit" value="Ask" class="btn btn-info">
			</div>
		</form>


				<center>
					Powered by <a href="http://lucida.ai">Lucida</a>
				</center>
				</td>
			</tr>
			<tr>
				<td></td>
				<td>
					<br>
					<a href="http://lucida.ai">
					<img src="{{ url_for('static', filename='image/lucida.jpg')}}" style="float: right; width: 100px; margin-right: 65px">
					</a>
				</td>
				<td>
					<br>
					<a href="http://djinn.clarity-lab.org">
					<img src="{{ url_for('static', filename='image/djinn.png')}}" style="float: left; width: 100px; margin-left: 5px">
					</a>
				</td>

		  </tr>
		</table>
	</div>

	<div class="pageFooter" style="margin-bottom: 0px">
		<span id="serverStatusBar" title="Number of available workers"></span>
		<select style="display: none;" id="servers" name="servers" style="margin-top:0em">
			<option value="{{ asr_addr_port }}/client/ws/speech|{{ asr_addr_port }}/client/ws/status" selected="selected">Lucida</option>
		</select>

		<p style="clear: both;">

		<pre id="log"></pre>
	</div>
</div>

<script src="{{ url_for('static', filename='js/dictate.js')}}"></script>
<script src="{{ url_for('static', filename='js/recorder.js')}}"></script>
<script src="{{ url_for('static', filename='js/recorderWorker.js')}}"></script>
<script src="{{ url_for('static', filename='js/mob.js')}}"></script>
<script src="{{ url_for('static', filename='js/resultSpeaker.js')}}"></script>
<script type="text/javascript">
var speakable = "{{ result }}";
if (speakable !== "" && speakable !== "None") {
	textToVoice("{{ result }}");
}
</script>
{% endblock %}

site/templates/learn.html
{% extends "base.html" %}

{% block content %}
<!-- https://www.imagely.com/wordpress-gallery-plugin/ -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/thumbnail.css')}}" type="text/css" media="all">

<div class="container">
	<div class="row">
		<p style="color:gray">Main » Learn</p>
	</div>

	{% if error %}
	<strong class=text-danger><p class="error">{{ error }}</p></strong>
	{% endif %}

	<div class="container">
		<div class="row">
			<p><h3>Add text knowledge:</h3></p>
		</div>
	</div>

	<div class="container">
		<form action="" method="post" enctype="multipart/form-data">
			<input name="op" type="hidden" value="add_text"></input>

			<div class="form-group">
				<label class="col-sm-3 control-label">Text: </label>
				<div class="col-sm-8">
					<input name="knowledge" class="form-control" placeholder="The capital of Italy is Rome">
				</div>
			</div>

			<div class="form-group">
				<input type="submit" value="Add" class="btn btn-info btn-sm">
			</div>
		</form>
	</div>

	<div class="container">
		<form action="" method="post" enctype="multipart/form-data">
			<input name="op" type="hidden" value="add_url"></input>

			<div class="form-group">
				<label class="col-sm-3 control-label">Url: </label>
				<div class="col-sm-8">
					<input name="knowledge" class="form-control" placeholder="https://en.wikipedia.org/wiki/Lucida">
				</div>
			</div>

			<div class="form-group">
				<input type="submit" value="Add" class="btn btn-info btn-sm">
			</div>
		</form>
	</div>

	<ul>
	{% for i in text %}
		<form action="" method="post" enctype="multipart/form-data">
			<input name="op" type="hidden" value="delete_text"></input>
			<input name="text_id" type="hidden" value={{ i['text_id'] }}></input>
			<div class="col-sm-10">
				<li>{% if i['type'] == 'url' %}<a href={{ i['text_data'] }}>{% endif %}{{ i['text_data'] }}{% if i['type'] == 'url' %}</a>{% endif %}</li>
			</div>
			<div class="col-sm-2">
				<input type="submit" value="Delete" class="btn btn-danger btn-sm">
			</div>
		</form>
	{% endfor %}
	</ul>

	<div class="container">
		<div class="row">
			<p><h3>Add image knowledge:</h3></p>
		</div>
	</div>

	<div class="container">
		<form action="" method=post enctype=multipart/form-data>
			<input name="op" type="hidden" value="add_image"></input>

			<div class="form-group">
				<input id="file_input" type="file" name="file" size="60">
				<p class="help-block">Upload your picture!</p>
			</div>

			<div class="form-group">
				<label class="col-sm-3 control-label">Label: </label>
				<div class="col-sm-6">
					<input name="label" class="form-control" placeholder="Eiffel Tower">
				</div>
			</div>

			<div class="form-group">
				<input id="file_submit" type="submit" value="Add" class="btn btn-info btn-sm">
			</div>
		</form>
	</div>
	
	{% for i in pictures %}
	<div class="ngg-gallery-thumbnail-box">
		<form action="" method="post" enctype="multipart/form-data">
			<input name="op" type="hidden" value="delete_image"></input>
			<input name="label" type="hidden" value={{ i['label'] }}></input>
			<input name="image_id" type="hidden" value={{ i['image_id'] }}></input>
			<div class="ngg-gallery-thumbnail">
				<img src="data:;base64,{{ i['data'] }}" style="max-width:none;" height="90"></img>
			</div>
			<div class="ngg-template-caption">{{ i['label'] }}
			<input type="submit" value="Delete" class="btn btn-danger btn-sm"></div>
		</form>
	</div>
	{% endfor %}
	
</div>

<br><br>
{% endblock %}

site/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class = "container">
	<div class="row">
		<p style="color:gray">Main » Log in</p>
	</div>

	<div class="page-header">
		<h1>Log in</h1>
	</div>

	<form action="" method=post enctype=multipart/form-data>
		<div class="form-group {% if form.username.errors %}has-error{% endif %}">
			<label>Username</label>
			<input id="login_username_input" name="username" class="form-control" placeholder="Username">
		{% for e in form.username.errors %}
			<p><strong class=text-danger>{{ e }}</strong></p>
		{% endfor %}
		</div>

		<div class="form-group {% if form.password.errors %}has-error{% endif %}">
			<label>Password</label>
			<input id="login_password_input" name="password" type="password" class="form-control" placeholder="Password">
		{% for e in form.password.errors %}
			<p><strong class=text-danger>{{ e }}</strong></p>
		{% endfor %}
		</div>

		<input id="submit" type="submit" class="btn btn-default" value="Submit">
	</form>

	{% if error %}
	<br>
	<p><strong>Please clear the following errors:</strong></p>
	<ul>
		{% for i in error %}
	<strong class=text-danger><p id="{% if i == 'Username does not exist' %}error_username{% else %}error_combo{% endif %}" class="error">{{ i }}</p></strong>
		{% endfor %}
	</ul>
	{% endif %}

	<br>
</div>
{% endblock %}

site/templates/signup.html
{% extends "base.html" %}

{% block content %}
<div class = "container">
	<div class="row">
		<p style="color:gray">Main » Sign up</p>
	</div>

	<div class="page-header">
		<h1>Register</h1>
	</div>

	<form action="{{ url_for('user.signup_route') }}" method=post enctype=multipart/form-data>
		<div class="form-group {% if form.username.errors %}has-error{% endif %}">
			<label>Username</label>
			<input id="new_username_input" name="username" class="form-control" placeholder="Username">
		{% for e in form.username.errors %}
			<p><strong class=text-danger>{{ e }}</strong></p>
		{% endfor %}
		</div>

		<div class="form-group {% if form.firstname.errors %}has-error{% endif %}">
			<label>First name</label>
			<input id="new_firstname_input" name="firstname" class="form-control" placeholder="First name">
		{% for e in form.firstname.errors %}
			<p><strong  class=text-danger>{{ e }}</strong></p>
		{% endfor %}					
		</div>

		<div class="form-group {% if form.lastname.errors %}has-error{% endif %}">
			<label>Last name</label>
			<input id="new_lastname_input" name="lastname" class="form-control" placeholder="Last name">
		{% for e in form.lastname.errors %}
			<p><strong class=text-danger>{{ e }}</strong></p>
		{% endfor %}
		</div>

		<div class="form-group {% if form.email.errors %}has-error{% endif %}">
			<label>Email Address</label>
			<input id="new_email_input" name="email" class="form-control" placeholder="Email">
		{% for e in form.email.errors %}
			<p><strong class=text-danger>{{ e }}</strong></p>
		{% endfor %}
		</div>

		<div class="form-group {% if form.password1.errors %}has-error{% endif %}">
			<label>Password</label>
			<input id="new_password1_input" name="password1" type="password" class="form-control" placeholder="Password">
		{% for e in form.password1.errors %}
			<p><strong class=text-danger>{{ e }}</strong></p>
		{% endfor %}
		</div>

		<div class="form-group {% if form.password2.errors %}has-error{% endif %}">
			<label>Confirm Password</label>
			<input id="new_password2_input" name="password2" type="password" class="form-control" placeholder="Confirm password">
		{% for e in form.password2.errors %}
			<p><strong class=text-danger>{{ e }}</strong></p>
		{% endfor %}
		</div>

		<input id="new_submit" type="submit" class="btn btn-default" value="Submit">
	</form>
	
	{% if error %}
		<br>
		<p><strong>Please clear the following errors:</strong></p>
		<ul>
			{% for i in error %}
				<strong class=text-danger><p class="error">{{ i }}</p></strong>
			{% endfor %}
		</ul>
	{% endif %}

	<br>
</div>
{% endblock %}